name: Check code

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.1

      - name: Lint
        run: make lint